
// Code generated by stanc 11a0fa51
#include <stan/model/model_header.hpp>
namespace bbglm_model_namespace {

template <typename T, typename S>
std::vector<T> resize_to_match__(std::vector<T>& dst, const std::vector<S>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, -1>
resize_to_match__(Eigen::Matrix<T, -1, -1>& dst, const Eigen::Matrix<T, -1, -1>& src) {
  dst.resize(src.rows(), src.cols());
  return dst;
}

template <typename T>
Eigen::Matrix<T, 1, -1>
resize_to_match__(Eigen::Matrix<T, 1, -1>& dst, const Eigen::Matrix<T, 1, -1>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, 1>
resize_to_match__(Eigen::Matrix<T, -1, 1>& dst, const Eigen::Matrix<T, -1, 1>& src) {
  dst.resize(src.size());
  return dst;
}
std::vector<double> to_doubles__(std::initializer_list<double> x) {
  return x;
}

std::vector<stan::math::var> to_vars__(std::initializer_list<stan::math::var> x) {
  return x;
}

inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math; 

static int current_statement__ = 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'bbglm.stan', line 9, column 2 to column 24)",
                                                      " (in 'bbglm.stan', line 10, column 2 to column 22)",
                                                      " (in 'bbglm.stan', line 27, column 2 to column 31)",
                                                      " (in 'bbglm.stan', line 28, column 2 to column 33)",
                                                      " (in 'bbglm.stan', line 30, column 4 to column 47)",
                                                      " (in 'bbglm.stan', line 29, column 18 to line 31, column 3)",
                                                      " (in 'bbglm.stan', line 29, column 2 to line 31, column 3)",
                                                      " (in 'bbglm.stan', line 13, column 2 to column 16)",
                                                      " (in 'bbglm.stan', line 14, column 2 to column 14)",
                                                      " (in 'bbglm.stan', line 15, column 2 to column 14)",
                                                      " (in 'bbglm.stan', line 16, column 2 to column 15)",
                                                      " (in 'bbglm.stan', line 17, column 2 to column 30)",
                                                      " (in 'bbglm.stan', line 18, column 2 to column 18)",
                                                      " (in 'bbglm.stan', line 20, column 4 to column 30)",
                                                      " (in 'bbglm.stan', line 21, column 4 to column 23)",
                                                      " (in 'bbglm.stan', line 22, column 4 to column 27)",
                                                      " (in 'bbglm.stan', line 19, column 18 to line 23, column 3)",
                                                      " (in 'bbglm.stan', line 19, column 2 to line 23, column 3)",
                                                      " (in 'bbglm.stan', line 24, column 2 to column 41)",
                                                      " (in 'bbglm.stan', line 2, column 2 to column 18)",
                                                      " (in 'bbglm.stan', line 3, column 2 to column 18)",
                                                      " (in 'bbglm.stan', line 4, column 2 to column 18)",
                                                      " (in 'bbglm.stan', line 5, column 2 to column 26)",
                                                      " (in 'bbglm.stan', line 6, column 2 to column 26)"};


class bbglm_model : public model_base_crtp<bbglm_model> {

 private:
  int pos__;
  int Jx;
  int Kx;
  Eigen::Matrix<double, -1, -1> X;
  std::vector<int> countx;
  std::vector<int> totalx;
 
 public:
  ~bbglm_model() { }
  
  std::string model_name() const { return "bbglm_model"; }
  
  bbglm_model(stan::io::var_context& context__,
              unsigned int random_seed__ = 0,
              std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    typedef double local_scalar_t__;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "bbglm_model_namespace::bbglm_model";
    (void) function__;  // suppress unused var warning
    
    try {
      
      pos__ = 1;
      context__.validate_dims("data initialization","Jx","int",
          context__.to_vec());
      
      current_statement__ = 20;
      Jx = context__.vals_i("Jx")[(1 - 1)];
      context__.validate_dims("data initialization","Kx","int",
          context__.to_vec());
      
      current_statement__ = 21;
      Kx = context__.vals_i("Kx")[(1 - 1)];
      current_statement__ = 22;
      validate_non_negative_index("X", "Jx", Jx);
      current_statement__ = 22;
      validate_non_negative_index("X", "Kx", Kx);
      context__.validate_dims("data initialization","X","double",
          context__.to_vec(Jx, Kx));
      X = Eigen::Matrix<double, -1, -1>(Jx, Kx);
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 22;
        assign(X_flat__, nil_index_list(), context__.vals_r("X"),
          "assigning variable X_flat__");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        for (size_t sym1__ = 1; sym1__ <= Kx; ++sym1__) {
          current_statement__ = 22;
          for (size_t sym2__ = 1; sym2__ <= Jx; ++sym2__) {
            current_statement__ = 22;
            assign(X,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              X_flat__[(pos__ - 1)], "assigning variable X");
            current_statement__ = 22;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 23;
      validate_non_negative_index("countx", "Jx", Jx);
      context__.validate_dims("data initialization","countx","int",
          context__.to_vec(Jx));
      countx = std::vector<int>(Jx, 0);
      
      current_statement__ = 23;
      assign(countx, nil_index_list(), context__.vals_i("countx"),
        "assigning variable countx");
      current_statement__ = 24;
      validate_non_negative_index("totalx", "Jx", Jx);
      context__.validate_dims("data initialization","totalx","int",
          context__.to_vec(Jx));
      totalx = std::vector<int>(Jx, 0);
      
      current_statement__ = 24;
      assign(totalx, nil_index_list(), context__.vals_i("totalx"),
        "assigning variable totalx");
      current_statement__ = 20;
      current_statement__ = 20;
      check_greater_or_equal(function__, "Jx", Jx, 0);
      current_statement__ = 21;
      current_statement__ = 21;
      check_greater_or_equal(function__, "Kx", Kx, 0);
      current_statement__ = 23;
      for (size_t sym1__ = 1; sym1__ <= Jx; ++sym1__) {
        current_statement__ = 23;
        current_statement__ = 23;
        check_greater_or_equal(function__, "countx[sym1__]",
                               countx[(sym1__ - 1)], 0);}
      current_statement__ = 24;
      for (size_t sym1__ = 1; sym1__ <= Jx; ++sym1__) {
        current_statement__ = 24;
        current_statement__ = 24;
        check_greater_or_equal(function__, "totalx[sym1__]",
                               totalx[(sym1__ - 1)], 0);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      current_statement__ = 2;
      validate_non_negative_index("betacoef", "Kx", Kx);
      num_params_r__ += Kx;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename T__>
  T__ log_prob(std::vector<T__>& params_r__, std::vector<int>& params_i__,
               std::ostream* pstream__ = 0) const {
    typedef T__ local_scalar_t__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "bbglm_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    
    try {
      local_scalar_t__ ssx;
      
      current_statement__ = 1;
      ssx = in__.scalar();
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        ssx = stan::math::lb_constrain(ssx, 0.001, lp__);
      } else {
        current_statement__ = 1;
        ssx = stan::math::lb_constrain(ssx, 0.001);
      }
      current_statement__ = 2;
      validate_non_negative_index("betacoef", "Kx", Kx);
      Eigen::Matrix<local_scalar_t__, -1, 1> betacoef;
      betacoef = Eigen::Matrix<local_scalar_t__, -1, 1>(Kx);
      
      current_statement__ = 2;
      betacoef = in__.vector(Kx);
      {
        current_statement__ = 8;
        validate_non_negative_index("Xb", "Jx", Jx);
        Eigen::Matrix<local_scalar_t__, -1, 1> Xb;
        Xb = Eigen::Matrix<local_scalar_t__, -1, 1>(Jx);
        
        current_statement__ = 8;
        for (size_t sym1__ = 1; sym1__ <= Jx; ++sym1__) {
          current_statement__ = 8;
          assign(Xb, cons_list(index_uni(sym1__), nil_index_list()),
            std::numeric_limits<double>::quiet_NaN(), "assigning variable Xb");
        }
        current_statement__ = 9;
        validate_non_negative_index("ax", "Jx", Jx);
        std::vector<local_scalar_t__> ax;
        ax = std::vector<local_scalar_t__>(Jx, 0);
        
        current_statement__ = 10;
        validate_non_negative_index("bx", "Jx", Jx);
        std::vector<local_scalar_t__> bx;
        bx = std::vector<local_scalar_t__>(Jx, 0);
        
        current_statement__ = 11;
        validate_non_negative_index("mux", "Jx", Jx);
        std::vector<local_scalar_t__> mux;
        mux = std::vector<local_scalar_t__>(Jx, 0);
        
        current_statement__ = 12;
        lp_accum__.add(gamma_log<propto__>(ssx, 1.0001, 0.0001));
        current_statement__ = 13;
        assign(Xb, nil_index_list(), multiply(X, betacoef),
          "assigning variable Xb");
        current_statement__ = 18;
        for (size_t n = 1; n <= Jx; ++n) {
          current_statement__ = 14;
          assign(mux, cons_list(index_uni(n), nil_index_list()),
            inv_logit(Xb[(n - 1)]), "assigning variable mux");
          current_statement__ = 15;
          assign(ax, cons_list(index_uni(n), nil_index_list()),
            (mux[(n - 1)] * ssx), "assigning variable ax");
          current_statement__ = 16;
          assign(bx, cons_list(index_uni(n), nil_index_list()),
            ((1 - mux[(n - 1)]) * ssx), "assigning variable bx");}
        current_statement__ = 19;
        lp_accum__.add(beta_binomial_log<propto__>(countx, totalx, ax, bx));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob() 
    
  template <typename RNG>
  void write_array(RNG& base_rng__, std::vector<double>& params_r__,
                   std::vector<int>& params_i__, std::vector<double>& vars__,
                   bool emit_transformed_parameters__ = true,
                   bool emit_generated_quantities__ = true,
                   std::ostream* pstream__ = 0) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "bbglm_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    
    try {
      double ssx;
      
      current_statement__ = 1;
      ssx = in__.scalar();
      current_statement__ = 1;
      ssx = stan::math::lb_constrain(ssx, 0.001);
      current_statement__ = 2;
      validate_non_negative_index("betacoef", "Kx", Kx);
      Eigen::Matrix<double, -1, 1> betacoef;
      betacoef = Eigen::Matrix<double, -1, 1>(Kx);
      
      current_statement__ = 2;
      betacoef = in__.vector(Kx);
      vars__.push_back(ssx);
      for (size_t sym1__ = 1; sym1__ <= Kx; ++sym1__) {
        vars__.push_back(betacoef[(sym1__ - 1)]);}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      current_statement__ = 3;
      validate_non_negative_index("pi", "Kx", Kx);
      std::vector<double> pi;
      pi = std::vector<double>(Kx, 0);
      
      current_statement__ = 4;
      assign(pi, cons_list(index_uni(1), nil_index_list()),
        inv_logit(betacoef[(1 - 1)]), "assigning variable pi");
      current_statement__ = 7;
      for (size_t j = 2; j <= Kx; ++j) {
        current_statement__ = 5;
        assign(pi, cons_list(index_uni(j), nil_index_list()),
          inv_logit((betacoef[(1 - 1)] + betacoef[(j - 1)])),
          "assigning variable pi");}
      current_statement__ = 3;
      for (size_t sym1__ = 1; sym1__ <= Kx; ++sym1__) {
        current_statement__ = 3;
        current_statement__ = 3;
        check_greater_or_equal(function__, "pi[sym1__]", pi[(sym1__ - 1)], 0);
      }
      current_statement__ = 3;
      for (size_t sym1__ = 1; sym1__ <= Kx; ++sym1__) {
        current_statement__ = 3;
        current_statement__ = 3;
        check_less_or_equal(function__, "pi[sym1__]", pi[(sym1__ - 1)], 1);}
      for (size_t sym1__ = 1; sym1__ <= Kx; ++sym1__) {
        vars__.push_back(pi[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array() 
    
  void transform_inits(const stan::io::var_context& context__,
                       std::vector<int>& params_i__,
                       std::vector<double>& vars__, std::ostream* pstream__) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      
      pos__ = 1;
      double ssx;
      
      current_statement__ = 1;
      ssx = context__.vals_r("ssx")[(1 - 1)];
      current_statement__ = 1;
      ssx = stan::math::lb_free(ssx, 0.001);
      current_statement__ = 2;
      validate_non_negative_index("betacoef", "Kx", Kx);
      Eigen::Matrix<double, -1, 1> betacoef;
      betacoef = Eigen::Matrix<double, -1, 1>(Kx);
      
      {
        std::vector<local_scalar_t__> betacoef_flat__;
        current_statement__ = 2;
        assign(betacoef_flat__, nil_index_list(),
          context__.vals_r("betacoef"), "assigning variable betacoef_flat__");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (size_t sym1__ = 1; sym1__ <= Kx; ++sym1__) {
          current_statement__ = 2;
          assign(betacoef, cons_list(index_uni(sym1__), nil_index_list()),
            betacoef_flat__[(pos__ - 1)], "assigning variable betacoef");
          current_statement__ = 2;
          pos__ = (pos__ + 1);}
      }
      vars__.push_back(ssx);
      for (size_t sym1__ = 1; sym1__ <= Kx; ++sym1__) {
        vars__.push_back(betacoef[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits() 
    
  void get_param_names(std::vector<std::string>& names__) const {
    
    names__.resize(0);
    names__.push_back("ssx");
    names__.push_back("betacoef");
    names__.push_back("pi");
    } // get_param_names() 
    
  void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.resize(0);
    std::vector<size_t> dims__;
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(Kx);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(Kx);
    dimss__.push_back(dims__);
    dims__.resize(0);
    
    } // get_dims() 
    
  void constrained_param_names(std::vector<std::string>& param_names__,
                               bool emit_transformed_parameters__ = true,
                               bool emit_generated_quantities__ = true) const {
    
    param_names__.push_back(std::string() + "ssx");
    for (size_t sym1__ = 1; sym1__ <= Kx; ++sym1__) {
      {
        param_names__.push_back(std::string() + "betacoef" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (size_t sym1__ = 1; sym1__ <= Kx; ++sym1__) {
        {
          param_names__.push_back(std::string() + "pi" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  void unconstrained_param_names(std::vector<std::string>& param_names__,
                                 bool emit_transformed_parameters__ = true,
                                 bool emit_generated_quantities__ = true) const {
    
    param_names__.push_back(std::string() + "ssx");
    for (size_t sym1__ = 1; sym1__ <= Kx; ++sym1__) {
      {
        param_names__.push_back(std::string() + "betacoef" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (size_t sym1__ = 1; sym1__ <= Kx; ++sym1__) {
        {
          param_names__.push_back(std::string() + "pi" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"ssx\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"betacoef\",\"type\":{\"name\":\"vector\",\"length\":" << Kx << "},\"block\":\"parameters\"},{\"name\":\"pi\",\"type\":{\"name\":\"array\",\"length\":" << Kx << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"ssx\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"betacoef\",\"type\":{\"name\":\"vector\",\"length\":" << Kx << "},\"block\":\"parameters\"},{\"name\":\"pi\",\"type\":{\"name\":\"array\",\"length\":" << Kx << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool emit_transformed_parameters__ = true,
                     bool emit_generated_quantities__ = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng__, params_r_vec, params_i_vec, vars_vec,
          emit_transformed_parameters__, emit_generated_quantities__, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    template <bool propto__, bool jacobian__, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto__,jacobian__,T_>(vec_params_r, vec_params_i, pstream);
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }

};
}
typedef bbglm_model_namespace::bbglm_model stan_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif


